window.SAMPLE_CATALOGUE_DATA = {
  "source": "sample-data",
  "updatedAt": "2026-05-20T00:00:00Z",
  "count": 57,
  "rows": [
    {
      "Record ID": "CAT-001",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "2 Bedroom Duplex Villa",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 20000.0,
      "Monthly Rate USD Approx": 5479.45,
      "Rate Notes": "Sample note: verify current availability and final rate before confirming booking.",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Reservations Team",
      "Contact Email": "reservations@example.com",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "https://www.marriott.com/en-us/hotels/dohdc-delta-hotels-city-center-doha/rooms/",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": 1,
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-002",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "2 Bedroom Villa with Pool",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 26000.0,
      "Monthly Rate USD Approx": 7123.29,
      "Rate Notes": "Sample note: verify current availability and final rate before confirming booking.",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Yassine",
      "Contact Email": "reservations@example.com",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-003",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "3 Bedroom Duplex Villa",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 27000.0,
      "Monthly Rate USD Approx": 7397.26,
      "Rate Notes": "Sample note: verify current availability and final rate before confirming booking.",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Reservations Team",
      "Contact Email": "reservations@example.com",
      "Contact Phone": "+974 66289665",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-004",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "3 Bedroom Villa with Pool",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 32000.0,
      "Monthly Rate USD Approx": 8767.12,
      "Rate Notes": "Sample note: verify current availability and final rate before confirming booking.",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Reservations Team",
      "Contact Email": "reservations@example.com",
      "Contact Phone": "+974 66289665",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-005",
      "Approval Status": "Approved",
      "Property Name": "Grand Hyatt Doha Hotel & Villas.",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Pearl Blvd, Doha, Qatar",
      "Unit Type": "2 Bedroom Ground Floor",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 34000.0,
      "Monthly Rate USD Approx": 9315.07,
      "Rate Notes": "Sample note: verify current availability and final rate before confirming booking.",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Complimentary access to Wi-Fi Internet\nComplimentary access to Gym, Spa and P...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Mariem Limem",
      "Contact Email": "mariem.limem@hyatt.com",
      "Contact Phone": "+974 30170178",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-006",
      "Approval Status": "Approved",
      "Property Name": "Grand Hyatt Doha Hotel & Villas.",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Pearl Blvd, Doha, Qatar",
      "Unit Type": "3 Bedroom Ground Floor",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 38000.0,
      "Monthly Rate USD Approx": 10410.96,
      "Rate Notes": "Sample note: verify current availability and final rate before confirming booking.",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Complimentary access to Wi-Fi Internet\nComplimentary access to Gym, Spa and P...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Mariem Limem",
      "Contact Email": "mariem.limem@hyatt.com",
      "Contact Phone": "+974 30170178",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-007",
      "Approval Status": "Approved",
      "Property Name": "Grand Hyatt Doha Hotel & Villas.",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Pearl Blvd, Doha, Qatar",
      "Unit Type": "4 Bedroom Ground Floor",
      "Bedrooms": 4,
      "Size SQM": "",
      "Monthly Rate QAR": 65000.0,
      "Monthly Rate USD Approx": 17808.22,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Complimentary access to Wi-Fi Internet\nComplimentary access to Gym, Spa and P...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Mariem Limem",
      "Contact Email": "mariem.limem@hyatt.com",
      "Contact Phone": "+974 30170178",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-008",
      "Approval Status": "Approved",
      "Property Name": "Katara Hills Doha, LXR Hotels & Resorts",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village, Doha, Qatar",
      "Unit Type": "3-Bedroom Villa with Pool",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 270000.0,
      "Monthly Rate USD Approx": 73972.6,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% Discount on Food & Beverage\n20% Discount on Spa Services\nComplimentary ac...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Ghofrane Touaiti ...",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-009",
      "Approval Status": "Approved",
      "Property Name": "Katara Hills Doha, LXR Hotels & Resorts",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village, Doha, Qatar",
      "Unit Type": "1-Bedroom Villa with Pool",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 120000.0,
      "Monthly Rate USD Approx": 32876.71,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% Discount on Food & Beverage\n20% Discount on Spa Services\nComplimentary ac...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Ghofrane Touaiti ...",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-010",
      "Approval Status": "Approved",
      "Property Name": "Maysan Doha, LXR Hotels & Resorts",
      "Category": "Villa",
      "Area": "Aspire / Baaya",
      "Address": "Baaya District, Furousiya St, Doha (near Villagio and Aspire)",
      "Unit Type": "2-Bedroom Villa with Pool",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 80000.0,
      "Monthly Rate USD Approx": 21917.81,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% Discount on Food & Beverage\n20% Discount on Spa Services\nComplimentary ac...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Ghofrane Touaiti ...",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-011",
      "Approval Status": "Approved",
      "Property Name": "Al Messila, a Luxury Collection Resort & Spa, Doha",
      "Category": "Villa",
      "Area": "",
      "Address": "Zone 36, Street 827, Building 21 (Um Al Saneem Street)",
      "Unit Type": "2 Bedroom Villa",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 45000.0,
      "Monthly Rate USD Approx": 12328.77,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Exclusive bathroom amenity line.\nExclusive bathroom amenity line.\nComplimenta...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "TAWFEQ ISSA",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-012",
      "Approval Status": "Approved",
      "Property Name": "Al Messila, a Luxury Collection Resort & Spa, Doha",
      "Category": "Villa",
      "Area": "",
      "Address": "Zone 36, Street 827, Building 21 (Um Al Saneem Street)",
      "Unit Type": "3 Bedroom Villa",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 100000.0,
      "Monthly Rate USD Approx": 27397.26,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Exclusive bathroom amenity line.\nExclusive bathroom amenity line.\nComplimenta...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "TAWFEQ ISSA",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-013",
      "Approval Status": "Approved",
      "Property Name": "The Chedi Katara Hotel & Resort",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village، 834 Shakespeare St, Doha, Qatar",
      "Unit Type": "2 Bedroom Villa",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 150000.0,
      "Monthly Rate USD Approx": 41095.89,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Breakfast only or Breakfast & Dinner\n20% off on Food & Beverage\n20% off at ...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-014",
      "Approval Status": "Approved",
      "Property Name": "The Chedi Katara Hotel & Resort",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village، 834 Shakespeare St, Doha, Qatar",
      "Unit Type": "3 Bedroom Villa",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 210000.0,
      "Monthly Rate USD Approx": 57534.25,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Breakfast only or Breakfast & Dinner\n20% off on Food & Beverage\n20% off at ...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-015",
      "Approval Status": "Approved",
      "Property Name": "City Centre Rotana",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "850 Conference Centre, Doha, Qatar",
      "Unit Type": "One Bedroom Apartment - City View",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 13000.0,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Outdoor swimming pool\nFree Wifi & Free parking\nFitness center & Spa\n4 restaur...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-016",
      "Approval Status": "Approved",
      "Property Name": "City Centre Rotana",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "850 Conference Centre, Doha, Qatar",
      "Unit Type": "TwoBedroom Apartment - City View",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 16000.0,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Outdoor swimming pool\nFree Wifi & Free parking\nFitness center & Spa\n4 restaur...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-017",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "Sky One Bedroom Suite",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 11000.0,
      "Monthly Rate USD Approx": 3013.7,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-018",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "Sky 2 bedroom apartment – city view",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 13000.0,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-019",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "Deluxe Two Bedroom +Maid Room",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 14000.0,
      "Monthly Rate USD Approx": 3835.62,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-020",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "Sky 3 bedroom apartment",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 19000.0,
      "Monthly Rate USD Approx": 5205.48,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-021",
      "Approval Status": "Approved",
      "Property Name": "Banyan Tree Doha",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "P.O. Box 4928 Al Khaleej St, Doha",
      "Unit Type": "2 Bedroom Apartment (155 sqm to 260 sqm)",
      "Bedrooms": 2,
      "Size SQM": "155",
      "Monthly Rate QAR": 16000.0,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits include:\n• All utilities (water, electricity, A/C)\n• Complimentary W...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-022",
      "Approval Status": "Approved",
      "Property Name": "Banyan Tree Doha",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "P.O. Box 4928 Al Khaleej St, Doha",
      "Unit Type": "3 Bedroom Apartment (225 sqm to 280 sqm)",
      "Bedrooms": 3,
      "Size SQM": "225",
      "Monthly Rate QAR": 20000.0,
      "Monthly Rate USD Approx": 5479.45,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits include:\n• All utilities (water, electricity, A/C)\n• Complimentary W...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-023",
      "Approval Status": "Approved",
      "Property Name": "Banyan Tree Doha",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "P.O. Box 4928 Al Khaleej St, Doha",
      "Unit Type": "4 Bedroom Apartment (290 sqm to 475 sqm)",
      "Bedrooms": 4,
      "Size SQM": "290",
      "Monthly Rate QAR": 42000.0,
      "Monthly Rate USD Approx": 11506.85,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits include:\n• All utilities (water, electricity, A/C)\n• Complimentary W...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-024",
      "Approval Status": "Approved",
      "Property Name": "Delta Hotels City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "Umm Arsaan St, Doha, Qatar",
      "Unit Type": "2 BR Apartment, City View (127sqm)",
      "Bedrooms": 2,
      "Size SQM": "127",
      "Monthly Rate QAR": 13000.0,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "24 h available maintenance team\n24 h available front desk assistance\n24 h ava...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-025",
      "Approval Status": "Approved",
      "Property Name": "Delta Hotels City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "Umm Arsaan St, Doha, Qatar",
      "Unit Type": "3 BR Apartment, City View (171sqm)\n3 BR Apartment, Sea View (171sqm)",
      "Bedrooms": 3,
      "Size SQM": "171",
      "Monthly Rate QAR": 15000.0,
      "Monthly Rate USD Approx": 4109.59,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "24 h available maintenance team\n24 h available front desk assistance\n24 h ava...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-026",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "Deluxe One Bedroom Suite with Balcony (99sqm)",
      "Bedrooms": 1,
      "Size SQM": "99",
      "Monthly Rate QAR": 12000.0,
      "Monthly Rate USD Approx": 3287.67,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-027",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "Suprior One Bedroom Suite with Balcony (99sqm)",
      "Bedrooms": 1,
      "Size SQM": "99",
      "Monthly Rate QAR": 13250.0,
      "Monthly Rate USD Approx": 3630.14,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-028",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "Two Bedroom Suite with Balcony (Inne...",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 15000.0,
      "Monthly Rate USD Approx": 4109.59,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-029",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "Deluxe Two Bedroom Suite without Balcony Inner Space 131sqm)",
      "Bedrooms": 2,
      "Size SQM": "131",
      "Monthly Rate QAR": 14250.0,
      "Monthly Rate USD Approx": 3904.11,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-030",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "Deluxe Two Bedroom Suite with Balcony (Inner ...",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 16000.0,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-031",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "Superior Two Bedroom Suite with Balcony (Inner S...",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 19500.0,
      "Monthly Rate USD Approx": 5342.47,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": "",
      "Contact Phone": "+974 44103260",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-032",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments City Center, Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Diplomatic Street Area 61, Street 806, Doha, Qatar",
      "Unit Type": "One Bedroom Premium: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 7000.0,
      "Monthly Rate USD Approx": 1917.81,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Inclusive of all expenses on utilities and electricity\nInclusive of 5 times p...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-033",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments City Center, Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Diplomatic Street Area 61, Street 806, Doha, Qatar",
      "Unit Type": "Two Bedrooms Deluxe: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 9000.0,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Inclusive of all expenses on utilities and electricity\nInclusive of 5 times p...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-034",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments City Center, Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Diplomatic Street Area 61, Street 806, Doha, Qatar",
      "Unit Type": "Three Bedrooms: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 13000.0,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Inclusive of all expenses on utilities and electricity\nInclusive of 5 times p...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-035",
      "Approval Status": "Approved",
      "Property Name": "Le Meridien City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Conference Centre, Doha, Qatar",
      "Unit Type": "One Bedroom : \n(May 2026 until 30 October 2026)",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 9000.0,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": "",
      "Pet Friendly": "YES (small breed)",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-036",
      "Approval Status": "Approved",
      "Property Name": "Le Meridien City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Conference Centre, Doha, Qatar",
      "Unit Type": "Two Bedrooms : (May 2026 until 30 October 2026)",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 11500.0,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": "",
      "Pet Friendly": "YES (small breed)",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-037",
      "Approval Status": "Approved",
      "Property Name": "Le Meridien City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Conference Centre, Doha, Qatar",
      "Unit Type": "Three Bedrooms: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 15500.0,
      "Monthly Rate USD Approx": 4246.58,
      "Rate Notes": "",
      "Pet Friendly": "YES (small breed)",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-038",
      "Approval Status": "Approved",
      "Property Name": "MARRIOTT MARQUIS CITY CENTER DOHA HOTEL",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "Omar Al Mukhtar Street, Area 61, Street #850, Doha, Qatar",
      "Unit Type": "One Bedroom :",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 9500.0,
      "Monthly Rate USD Approx": 2602.74,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-039",
      "Approval Status": "Approved",
      "Property Name": "MARRIOTT MARQUIS CITY CENTER DOHA HOTEL",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "Omar Al Mukhtar Street, Area 61, Street #850, Doha, Qatar",
      "Unit Type": "Two Bedrooms :",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 11500.0,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-040",
      "Approval Status": "Approved",
      "Property Name": "MARRIOTT MARQUIS CITY CENTER DOHA HOTEL",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "Omar Al Mukhtar Street, Area 61, Street #850, Doha, Qatar",
      "Unit Type": "Three Bedrooms:",
      "Bedrooms": 3,
      "Size SQM": "",
      "Monthly Rate QAR": 15500.0,
      "Monthly Rate USD Approx": 4246.58,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-041",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments Doha Le Mirage City Walk",
      "Category": "Serviced Apartment",
      "Area": "Msheireb / Bin Mahmoud",
      "Address": "Ibn Mahmoud Street, Bin Mahmoud / Musherib district/near Bin Mahmoud Metro St...",
      "Unit Type": "One Bedroom-HK (May 2026 until 30 Aug 2026)",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 9000.0,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Fully furnished apartments with air-conditioning, 55” Smart TV, Wi-Fi, in-r...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-042",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments Doha Le Mirage City Walk",
      "Category": "Serviced Apartment",
      "Area": "Msheireb / Bin Mahmoud",
      "Address": "Ibn Mahmoud Street, Bin Mahmoud / Musherib district/near Bin Mahmoud Metro St...",
      "Unit Type": "Two Bedrooms-HK",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 11500.0,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Fully furnished apartments with air-conditioning, 55” Smart TV, Wi-Fi, in-r...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-043",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments Doha Le Mirage City Walk",
      "Category": "Serviced Apartment",
      "Area": "Msheireb / Bin Mahmoud",
      "Address": "Ibn Mahmoud Street, Bin Mahmoud / Musherib district/near Bin Mahmoud Metro St...",
      "Unit Type": "Two Bedrooms-HK Duplex",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": "",
      "Monthly Rate USD Approx": "",
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Fully furnished apartments with air-conditioning, 55” Smart TV, Wi-Fi, in-r...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-044",
      "Approval Status": "Approved",
      "Property Name": "Le Mirage Downtown:",
      "Category": "Serviced Apartment",
      "Area": "Ras Abu Abboud",
      "Address": "Building 30| Street 210, Ras Abu Abboud Street| Zone 16",
      "Unit Type": "One Bedroom",
      "Bedrooms": 1,
      "Size SQM": "",
      "Monthly Rate QAR": 9000.0,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-045",
      "Approval Status": "Approved",
      "Property Name": "Le Mirage Downtown:",
      "Category": "Serviced Apartment",
      "Area": "Ras Abu Abboud",
      "Address": "Building 30| Street 210, Ras Abu Abboud Street| Zone 16",
      "Unit Type": "Two Bedrooms (May 2026 until 31 Aug 2026)",
      "Bedrooms": 2,
      "Size SQM": "",
      "Monthly Rate QAR": 11500.0,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-046",
      "Approval Status": "Approved",
      "Property Name": "Baraha Town",
      "Category": "Serviced Apartment",
      "Area": "Mesaimeer",
      "Address": "6FRR+XJQ, Mesaimeer Rd, Doha, Qatar",
      "Unit Type": "Studio (41 sqm)",
      "Bedrooms": "Studio",
      "Size SQM": "41",
      "Monthly Rate QAR": 5000.0,
      "Monthly Rate USD Approx": 1369.86,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-047",
      "Approval Status": "Approved",
      "Property Name": "Baraha Town",
      "Category": "Serviced Apartment",
      "Area": "Mesaimeer",
      "Address": "6FRR+XJQ, Mesaimeer Rd, Doha, Qatar",
      "Unit Type": "One Bedroom-HK (91 sqm)",
      "Bedrooms": 1,
      "Size SQM": "91",
      "Monthly Rate QAR": 6500.0,
      "Monthly Rate USD Approx": 1780.82,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-048",
      "Approval Status": "Approved",
      "Property Name": "Le Mirage Icon",
      "Category": "Serviced Apartment",
      "Area": "",
      "Address": "Nasr Bin Sayyar Street ,7GH7+9QX, Doha, Qatar",
      "Unit Type": "2 Bedroom-Hk (146 sqm)",
      "Bedrooms": 2,
      "Size SQM": "146",
      "Monthly Rate QAR": 10500.0,
      "Monthly Rate USD Approx": 2876.71,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-049",
      "Approval Status": "Approved",
      "Property Name": "InterContinental Doha The City",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Doha West Bay /Near DECC Metro",
      "Unit Type": "One bedroom – residence suite (100-124 sq.m)",
      "Bedrooms": 1,
      "Size SQM": "100-124",
      "Monthly Rate QAR": 11000.0,
      "Monthly Rate USD Approx": 3013.7,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits:\nFully covered water and electricity bills\nComplimentary WiFi\n20% di...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-050",
      "Approval Status": "Approved",
      "Property Name": "InterContinental Doha The City",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Doha West Bay /Near DECC Metro",
      "Unit Type": "Two bedroom – residence suite (127-147 sq.m)",
      "Bedrooms": 2,
      "Size SQM": "127-147",
      "Monthly Rate QAR": 14500.0,
      "Monthly Rate USD Approx": 3972.6,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits:\nFully covered water and electricity bills\nComplimentary WiFi\n20% di...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-051",
      "Approval Status": "Approved",
      "Property Name": "InterContinental Doha The City",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Doha West Bay /Near DECC Metro",
      "Unit Type": "Three bedroom – residence suite (146-185 sq.m)",
      "Bedrooms": 3,
      "Size SQM": "146-185",
      "Monthly Rate QAR": 16500.0,
      "Monthly Rate USD Approx": 4520.55,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits:\nFully covered water and electricity bills\nComplimentary WiFi\n20% di...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-052",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "Standard 1 BR Apartment (65 sqm)",
      "Bedrooms": 1,
      "Size SQM": "65",
      "Monthly Rate QAR": 10000.0,
      "Monthly Rate USD Approx": 2739.73,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Complimentary High-Speed Wi-Fi Internet.\n• 20% discount in se...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-053",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "Premuim One Bedroom Apartment (86 sqm)",
      "Bedrooms": 1,
      "Size SQM": "86",
      "Monthly Rate QAR": 11000.0,
      "Monthly Rate USD Approx": 3013.7,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Complimentary High-Speed Wi-Fi Internet.\n• 20% discount in se...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-054",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "Standard 2 BR Apartment Standard (105 sqm)",
      "Bedrooms": 2,
      "Size SQM": "105",
      "Monthly Rate QAR": 13000.0,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Complimentary High-Speed Wi-Fi Internet.\n• 20% discount in se...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-055",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "Premuim Standard 2 BR Apartment (146 sqm)",
      "Bedrooms": 2,
      "Size SQM": "146",
      "Monthly Rate QAR": 14000.0,
      "Monthly Rate USD Approx": 3835.62,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Complimentary High-Speed Wi-Fi Internet.\n• 20% discount in se...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-056",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "Three Bedroom Apartment (173 sqm)",
      "Bedrooms": 3,
      "Size SQM": "173",
      "Monthly Rate QAR": 16000.0,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": "",
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Complimentary High-Speed Wi-Fi Internet.\n• 20% discount in se...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    },
    {
      "Record ID": "CAT-057",
      "Approval Status": "Approved",
      "Property Name": "Retaj Hotels & Hospitality - Retaj Baywalk Residence",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "( VIVA Bhariya 8 ) Retaj Baywalk Residence The  Pearl, Street 140, Zone 66, T...",
      "Unit Type": "Standard One Bedroom (77sqm)",
      "Bedrooms": 1,
      "Size SQM": "77",
      "Monthly Rate QAR": 9500.0,
      "Monthly Rate USD Approx": 2602.74,
      "Rate Notes": "",
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Retaj Baywalk Residence provides residents all the amenities, utilities and s...",
      "Cancellation Policy": "We require one (1) month notice for cancellation **Prices may vary on the un...",
      "Contact Name": "Farah Aissou",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Unit Detail URL": "",
      "Unit Video URL": "",
      "Unit Image URL": "",
      "Unit Display Order": "",
      "Booking / Display Notes": "",
      "Internal Notes": "",
      "Last Updated": "2026-05-20"
    }
  ]
};
